### PR TITLE
Support both Kodi 19 and older Kodi versions

### PR DESCRIPTION
**Pull request by sagiben**
Tested on Kodi 18.5 and Kodi 19 ALPHA

### CODE REVIEW

**Comment by CaTzil** [comment]
Thank you!
Should I revert your previous change?

**Comment by sagiben** [comment]
No, do not revert, just apply this change on top

**Comment by CaTzil** [comment]
Will create a release at the evening, thank you :]

**Comment by CaTzil** [comment]
Just released it as 1.2.0, thank you again :]

**Pull request merged**
